# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff1689be5fdd05995b647b4577da2a4e5fe86fc70045b84ee324d1bb290e7382ea5722d06aebe0c2f038b6e2f97d80908857a38c80fe26b83a7840ba40a3a8e0

test:
  secret_key_base: c0f8506a99a90fb09ca0f188c850a524c241c686f369519a5d8c97ef6f57593102b5195bc153c9d90e4e874f3026b0754f2b3996cfcbc31cebe7acb4977b99ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
